# Generated by Django 6.0.5 on 2026-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='superheroes'),
        ),
    ]
